[FEAT] 마이페이지 유저정보 API
Make-A-Wish-Sopt/Make-A-Wish-Server pull request #29
Opened 2023-05-13 13:29 UTC by yujindonut

```
- commit message가 적절한지 확인해주세요.
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.
```

## ✨ 관련 이슈
closed #21 

## ✨ 변경 사항 및 이유
마이페이지에서 유저정보(최근 소원의 정보 수정) 수정 API 개발

## ✨ PR Point

Wish(자신이 만든 wish중 가장 최근 wish) 와 User 테이블의 데이터가 모두 수정됩니다.

<img width="1125" alt="image" src="https://github.com/Make-A-Wish-Sopt/Make-A-Wish-Server/assets/78431728/8b3f8d3b-64b2-46d0-b7de-0b97b4aafc1d">
<img width="1123" alt="image" src="https://github.com/Make-A-Wish-Sopt/Make-A-Wish-Server/assets/78431728/bebd0d7f-0160-4d0a-b1a1-038b7a8d3adc">

2023-05-14 06:04 UTC, thguss requested changes
수고하셨습니다! update(set&save) 부분과 print 삭제만 수정 반영 부탁드려요~!
그 외 리뷰는 참고하셔서 반영하실 것만 반영하하면 될 것 같습니다 :)

2023-05-14 06:04 UTC, thguss commented on src/main/java/com/sopterm/makeawish/controller/UserController.java
> +    @PostMapping("")
추가 uri 정보가 붙지 않는다면 @PostMapping 만 적어주셔도 됩니다!

2023-05-14 06:04 UTC, thguss commented on src/main/java/com/sopterm/makeawish/controller/UserController.java
> +    @PostMapping("")
수정 API라면 PATCH 또는 PUT 이면 논리적으로도 더 자연스러울 것 같아요 :)

2023-05-14 06:04 UTC, thguss commented on src/main/java/com/sopterm/makeawish/domain/user/User.java
> +        if(account == null) account = this.account.getAccount();
가독성을 위해서 if 한 줄 보다는 {}을 추가해주시면 좋을 것 같아요!

2023-05-14 06:04 UTC, thguss commented on src/main/java/com/sopterm/makeawish/repository/WishRepository.java
> +	boolean existsWishByWisherOrderByEndAtDesc(User wisher);
boolean 형식인데 Order By 및 Desc 정렬 옵션이 들어가는 이유가 뭔가요??

2023-05-14 06:04 UTC, thguss commented on src/main/java/com/sopterm/makeawish/repository/WishRepository.java
> +	Wish findFirstByWisherOrderByEndAtDesc(User wisher);
단일 클래스 타입인데 OrderByEndAtDesc 와 같이 정렬 옵션이 들어가는 이유가 궁금해요!

2023-05-14 06:04 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/WishService.java
> +		userRepository.save(user);
내 정보 수정에서 user을 save하는 이유가 궁금해요!

2023-05-14 06:04 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/WishService.java
> +		userRepository.save(user);
user의 정보를 수정하는 목적이라면, User Entity 내에서 set (this.data = data) 만 해주셔도 자동으로 수정됩니다!

2023-05-14 06:04 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/WishService.java
> +		return MypageWishUpdateResponseDTO.from(wishRepository.save(userWish));
여기도 Wish 엔티티에 set만 해주면 알아서 수정되어서 save까지 안해도 됩니다!

2023-05-14 06:04 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/WishService.java
> +		System.out.println(wish.getEndAt());
print문 삭제 부탁드려요!

2023-05-14 06:45 UTC, wlwpfh approved these changes
수고하셨습니다!!

2023-05-14 06:45 UTC, wlwpfh commented on src/main/java/com/sopterm/makeawish/config/jwt/JwtTokenFilter.java
> +                uri.startsWith("/swagger-ui") || (uri.startsWith("/api/v1/wishes") && request.getMethod().equals("GET")) || uri.startsWith("/health")) {
`GET` 말고 `HttpMethod.GET` 은 어떤가요..?!!

2023-05-14 23:42 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/controller/UserController.java
> +    @PostMapping("")
그렇겠네요!! 수정하도록 하겠습니다 ~

2023-05-14 23:42 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/domain/user/User.java
> +        if(account == null) account = this.account.getAccount();
넵 감사합니당!!

2023-05-14 23:44 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/repository/WishRepository.java
> +	Wish findFirstByWisherOrderByEndAtDesc(User wisher);
자신의 wish가 여러개일 경우에  .. 일년에 한번 올릴 수 있기에, 가장 최근의 wish를 가져오기 위함이였습니다..!

2023-05-14 23:45 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/service/WishService.java
> +		userRepository.save(user);
맞아요!ㅠㅠㅠㅠ 수정 목적이였는데 그부분을 놓치고 바로바로 save 해버렸네요 ... 감사합니다!

2023-05-14 23:45 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/service/WishService.java
> +		System.out.println(wish.getEndAt());
헉 넵!!!!!

2023-05-14 23:45 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/config/jwt/JwtTokenFilter.java
> +                uri.startsWith("/swagger-ui") || (uri.startsWith("/api/v1/wishes") && request.getMethod().equals("GET")) || uri.startsWith("/health")) {
그게 훨씬 직관적이고 이해하기 편할 것 같아요! 감사합니당!

2023-05-14 23:55 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/repository/WishRepository.java
> +	boolean existsWishByWisherOrderByEndAtDesc(User wisher);
그러게요! 수정하도록 하겠습니다!

2023-05-15 00:04 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/controller/UserController.java
> +    @PostMapping("")
뭐로 할지 고민했는데 .. 멱등성을 가진 put으로 변경하려고 하는데 어떨까요! put은 요청하지 않은 값을 Null로 변경할 수도 있지만, 안에서 null 처리를 해주었으니 patch보다는 Put .. 이 적절해보인다고 생각해서요!

2023-05-15 00:15 UTC, thguss commented on src/main/java/com/sopterm/makeawish/repository/WishRepository.java
> +	Wish findFirstByWisherOrderByEndAtDesc(User wisher);
아하 findFirst를 사용하셨군요! 이 부분을 놓쳤었네요 ㅠㅠ
그런 것이라면 [top 관련 쿼리](https://simple-ing.tistory.com/46)도 있는데 비교해보고 더 적절한 것을 사용해도 좋을 것 같아요!
또한, 일년에 한 번 올릴 수 있는 것이라면 올해에 해당하는 wish(wish.createdAt.year=now.year)가 존재한다면 그 값을, 없으면 빈 값으로 가져오는 Optional 방식은 혹시 어떤가요?? 개인적인 의견임다~!

2023-05-15 00:17 UTC, thguss approved these changes

2023-05-15 00:30 UTC, yujindonut commented
헐 나 바보같이 커밋 메세지 완전 거꿀로 썼어...
ㅇ아아아악

2023-05-15 00:43 UTC, merged