[CHORE] 카카오 로직 변경 요청
Make-A-Wish-Sopt/Make-A-Wish-Server pull request #42
Opened 2023-05-27 15:20 UTC by yujindonut

```
- commit message가 적절한지 확인해주세요.
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.
```

## ✨ 관련 이슈
closed #41 

## ✨ 변경 사항 및 이유
카카오 인가 코드를 받아서 나머지 처리는 백에서 처리하고 우리의 internal access token을 발급해주는 코드로 변경

## ✨ PR Point
user에 nickname 필드 넣었습니다! 
회원가입시, social Id , nickname등을 넣습니다.

2023-05-28 04:45 UTC, thguss requested changes
수고하셨습니다!!
리뷰 확인 부탁드려요 :)

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/domain/user/User.java
> +    }
this.account = new Account(null, null, null);
도 추가하는 것이 좋을 것 같아요. 칼럼 값은 null이더라도 account 필드 자체는 값을 미리 할당해주어야 한다고 생각합니다!

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/dto/auth/LoginRequest.java
> +public class LoginRequest {
DTO 역할을 하는 클래스인가요??
맞다면 다른 DTO와 같이 RECORD 형식이 아닌 다른 클래스 형식으로 나타낸 이유가 궁금합니다!

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/dto/auth/LoginResponse.java
> +public class LoginResponse {
LoginRequest와 같은 코멘트입니다.

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/dto/auth/SignupRequest.java
> +public class SignupRequest {
여기도..!!

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/AuthService.java
> +    private final Map<SocialType, SocialLoginService> socialLogins = new EnumMap<>(SocialType.class);
해당 변수의 역할과 타입이 맵인 이유가 궁금해요!

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +        System.out.println(code);
삭제 부탁드려요!

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +            System.out.println(kakaoAccessToken);
삭제 부탁드려요!

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +        System.out.println(socialId);
삭제 부탁드려용

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +                .orElseThrow(() -> new EntityNotFoundException("존재하지 않는 유저입니다."));
Message ENUM 값으로 가져오면 더 좋을 것 같아요!

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +        System.out.println(code);
삭제 부탁드려요 ㅎㅎ

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +        System.out.println(responseBody);
sout 삭제 부탁드려요~!

2023-05-28 04:45 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +            System.out.println(result);
삭제..!

2023-05-28 06:18 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +        System.out.println(socialId);
헉 넵!

2023-05-28 06:26 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/domain/user/User.java
> +    }
헉 그러네요! 좋습니당!

2023-05-28 06:48 UTC, thguss reviewed
인텔리제이에서 잡아준 경고 관련 리뷰 드립니다~

2023-05-28 06:48 UTC, thguss commented on src/main/java/com/sopterm/makeawish/dto/auth/AuthSignInResponseDto.java
>          public static AuthSignInResponseDto from (String accessToken, String refreshToken, boolean isRegistered) {
isRegistered 칼럼을 삭제했다면, 생성자 파라미터에서도 제외해주어야 할 것 같아요!

2023-05-28 06:48 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/AuthService.java
>      private final JwtTokenProvider jwtTokenProvider;
요거 2개는 사용하지 않는 변수 같은데..!! 맞다면 삭제하는 것이 좋을 것 같아요~

2023-05-28 06:48 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +    }
요 메소드 인텔리제이에서 미사용 메소드라고 나와서 그런데 어디서 사용되나요??
사용되지 않는다면 삭제해주는 것이 좋을 것 같아요!

2023-05-28 08:11 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/dto/auth/LoginRequest.java
> +public class LoginRequest {
record 형태로 다시 통일감있게 수정했습니다! 
급하게 참고 자료들을 보고 만드느라 ,,  ㅠ 0 ㅠ,, DTO형태로 만들었는데, 다시 record로 수정했습니다!

2023-05-28 08:13 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/service/AuthService.java
> +    private final Map<SocialType, SocialLoginService> socialLogins = new EnumMap<>(SocialType.class);
나중에 추후, Google이나 다른 Social Auth 가 추가될 경우를 대비해서 추상화하도록 한것입니다..
근데 api endpoint 자체가 kakao를 위한 api여서 .. 어떻게 해야할지 모르겠습니다 하하

2023-05-28 08:14 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/dto/auth/AuthSignInResponseDto.java
>          public static AuthSignInResponseDto from (String accessToken, String refreshToken, boolean isRegistered) {
넵 수정했습니다! 후하하 너무 급하게 올린게 티나네요 ..

2023-05-28 08:33 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +                .orElseThrow(() -> new EntityNotFoundException("존재하지 않는 유저입니다."));
해당 함수 삭제하도록 했습니다!

2023-05-28 14:42 UTC, thguss reviewed
수고많으셔요~! 리프레시 기간도 걸려서 시간 좀 넉넉하니 리뷰 전보다 많이 달아봤습니다 ㅎㅎ
여유로우니 리뷰와 코드에 대해서 모두 합의하고 approve 들어가면 좋을 것 같아 comment로 남깁니다!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
> +	INVALID_SOCIAL_TYPE("유효하지 않는 소셜 타입입니다."),
혹시 어디서 사용되는 enum 값일까요??

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
>  	private final String message;
코드 가독성을 위해 enum 값과 final 변수는 한 줄 띄어쓰기 하는 것이 좋을 것 같아요. 개인적인 의견입니당 :)

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/config/SecurityConfig.java
> +                .requestMatchers("/api/v1/auth/**").permitAll()
하위 처리까지 굳!!

해당 PR 내용은 아니지만, 위에 `@EnableMethodSecurity(prePostEnabled = true)` 에서 `prePostEnabled = true`는 default 값으로 알고 있어요. 따라서 (...) 부분은 삭제해줘도 좋을 것 같아요!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/domain/user/SocialType.java
> +                .orElseThrow(() -> new IllegalArgumentException(INCORRECT_WISH.getMessage()));
이런 예외처리 아주 맘에 쏙 드네용 :D

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/domain/user/User.java
> +        this.nickname = name == null ? this.nickname : name;
`name == null` 요 부분을 (name == null) 와 같이 괄호를 치거나, isNull(name) 처럼 Objects로 감싸면 가독성이 더 좋아질 것 같아요~

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/domain/user/User.java
> +        this.nickname = name == null ? this.nickname : name;
birthEndAt, birthStartAt, phoneNumber도 위와 같은 코멘트 드려요-!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/controller/UserController.java
>                      """)
19줄에 `import static org.springframework.http.HttpStatus.NO_CONTENT;` 부분은 사용되지 않는 것 같으니 삭제해주면 좋을 것 같아요! 코멘트 줄이 안 잡혀서 31줄에 리뷰 남깁니다 ㅠㅠ

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/domain/user/User.java
>      }
해당 메소드는 사용되지 않는 것 같아요! 사용할 곳이 없다면 지워주면 좋을 것 같습니다!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/dto/auth/AuthLoginRequestDto.java
> +    public static AuthLoginRequestDto from(String accessToken, String nickname, String email) {
해당 DTO가 사용되는 곳이 어디인가요??
사용되는 곳이 보이지 않아서요..!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/dto/auth/AuthLoginResponseDto.java
> +    }
해당 DTO가 사용되는 곳도 궁금해요!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/dto/auth/AuthSignInRequestDto.java
> +        String email,
굳!! email 형식을 사용한다면 @Email 같은 것을 써봐도 좋을 것 같다는 생각이 드네요-!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/dto/auth/AuthSignInResponseDto.java
>          public static AuthSignInResponseDto from (String accessToken, String refreshToken, boolean isRegistered) {
isRegistered 값이 삭제되었으니, `from (String accessToken, String refreshToken, boolean isRegistered)`에서 `from (String accessToken, String refreshToken)`으로 변경해서 미사용 파라미터는 삭제해주는 것이 좋을 것 같아요 :)

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/repository/UserRepository.java
>      public boolean existsByRefreshToken(String refreshToken);
해당 메소드는 어디서 사용되나요??

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/repository/UserRepository.java
>      public Long findIdBySocialId(String socialId);
인터페이스 파일에서는 public 같은 접근제어자를 사용하지 않고 메소드만 포함해요!
public은 지워주는 것이 좋을 것 같아요~

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/repository/UserRepository.java
>      public Long findIdBySocialId(String socialId);
해당 메소드들도 사용되는 곳이 보이지 않아서 그런데 어디서 사용되나요??

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/AuthService.java
>  import com.sopterm.makeawish.config.jwt.JwtTokenProvider;
사용되지 않는 임포터 같아요!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/AuthService.java
>  import com.sopterm.makeawish.repository.UserRepository;
여기도 사용되지 않는 임포터 같아요!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/SocialLoginService.java
> +public interface SocialLoginService {
오호 요런 용도의 서비스도 있군요?? 배워갑니다~

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/WishService.java
> +				.findFirstByWisherOrderByEndAtDesc(getUser(userSocialId)).orElse(null);
User를 userId가 아닌 socialId로 가져오는 이유가 있을까요??
개인적으로 혹시라도 다른 소셜 서비스에서 socialId가 중복되는 현상이 발생한다면 치명적이기 때문에, 이전처럼 userId를 사용하는 방향이 바람직하다고 생각하는데 어떠신가요??

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +import com.sopterm.makeawish.dto.auth.AuthGetTokenResponseDto;
사용되지 않는 임포터 같아요!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +import jakarta.persistence.EntityNotFoundException;
사용되지 않는 임포터 같아요!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +        System.out.println(response);
System.out.println 삭제가 되지 않은 것 같아요!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +        System.out.println(responseBody);
삭제가 되지 않았어요!

2023-05-28 14:42 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
> +        System.out.println(code);
삭제가 되지 않았어요!

2023-05-28 14:42 UTC, thguss reviewed
수고많으셔요~! 리프레시 기간도 걸려서 시간 좀 넉넉하니 리뷰 전보다 많이 달아봤습니다 ㅎㅎ
여유로우니 리뷰와 코드에 대해서 모두 합의하고 approve 들어가면 좋을 것 같아 comment로 남깁니다!

2023-05-28 14:43 UTC, thguss commented on src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
> +	INVALID_SOCIAL_TYPE("유효하지 않는 소셜 타입입니다."),
INVALID_SOCIAL_TYPE 값이요!

2023-05-29 04:00 UTC, wlwpfh approved these changes
정말 수고 많으셨습니다 👍👍👍!!!!

2023-05-29 04:00 UTC, wlwpfh commented on src/main/java/com/sopterm/makeawish/domain/user/SocialType.java
> +                .orElseThrow(() -> new IllegalArgumentException(INCORRECT_WISH.getMessage()));
정말 깔끔하네요..! 👍

2023-05-29 04:00 UTC, wlwpfh commented on src/main/java/com/sopterm/makeawish/service/AuthService.java
> +        socialLogins.put(SocialType.KAKAO, kakaoLoginService);
배워가요!! 👍👍

2023-06-06 23:56 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/domain/user/User.java
> +        this.nickname = name == null ? this.nickname : name;
isNull() 메소드 사용하는거 넘 좋네요!!

2023-06-07 00:01 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/controller/UserController.java
>                      """)
헉 닫혀있어서 놓쳤네요,, 소현이 짱입니다

2023-06-07 00:05 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/dto/auth/AuthLoginRequestDto.java
> +    public static AuthLoginRequestDto from(String accessToken, String nickname, String email) {
맞아요 지워줘도 되는 Dto입니다..

2023-06-07 00:05 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/dto/auth/AuthSignInRequestDto.java
> +        String email,
좋씁니당~!~!~!

2023-06-07 00:07 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/repository/UserRepository.java
>      public boolean existsByRefreshToken(String refreshToken);
미사용 메소드 모두 삭제하도록 하겠습니다!

2023-06-08 03:55 UTC, thguss approved these changes
굳!! 많은 리뷰 보고 반영하느라 수고 많았어요 ㅠ.ㅠ

2023-06-08 04:15 UTC, merged