[CHORE] 토큰 로직변경에 따른 유저 조회 방법 수정
Make-A-Wish-Sopt/Make-A-Wish-Server pull request #57
Opened 2023-06-30 00:32 UTC by yujindonut

## ✨ 변경 사항 및 이유
토큰 로직이 변경됨에 따라, 토큰에서 유저를 검색하는 로직 변경

2023-06-30 07:07 UTC, thguss requested changes
수고하셨습니다!

리뷰를 하면서 한 가지 요청하고 싶었던 점은, 이슈 외의 변경 사항(Principal 변경, 특히 도메인 쪽(User) 변경) 부분은 어떤 이유로 어떠하게 변경했는지 PR에 추가적으로 적어주시면 좀 더 수월하게 리뷰할 수 있을 것 같았어요! (이 부분은 저도 PR을 올릴 때 좀 더 신경쓰도록 하겠습니다 ㅎㅎ)

또한, Refresh Token 발급이 추가되었으니 클라이언트에게 해당 사항 전달을 부탁드려도 될까요??

Refresh Token 발급까지 빠르게 작업해주셔서 감사해요 :)
리뷰 확인 후 재언급 주시면 다시 리뷰 달겠습니다!

2023-06-30 07:07 UTC, thguss commented on src/main/java/com/sopterm/makeawish/controller/AuthController.java
> +    public ResponseEntity<ApiResponse> getToken(@Parameter(hidden = true) @AuthenticationPrincipal InternalMemberDetails memberDetails)
Refresh Token이 아닌 InternalMemberDetails을 받는 이유가 있나요??
제가 이해하는 로직은 회원마다 가지고 있는 Refresh Token 검증 후 Access Token을 재발급해주는 것으로 알고 있어 물어봅니다!

2023-06-30 07:07 UTC, thguss commented on src/main/java/com/sopterm/makeawish/controller/AuthController.java
> +        System.out.println(memberDetails.getId());
println 부분은 제거해주세요!

2023-06-30 07:07 UTC, thguss commented on src/main/java/com/sopterm/makeawish/controller/CakeController.java
> +    public ResponseEntity<ApiResponse> getPresents(@Parameter(hidden = true) @AuthenticationPrincipal InternalMemberDetails memberDetails,
Principal에서 InternalMemberDetails으로 변경된 이유가 뭔가요??

2023-06-30 07:07 UTC, thguss commented on src/main/java/com/sopterm/makeawish/domain/user/InternalMemberDetails.java
> +    private final String userNickName;
닉네임을 생각해서 바꾼 변수명이라면, nickname으로 변경해도 좋을 것 같습니다.
user가 붙어서 변수명이 길어짐으로써 가독성 부분에서 좋지 않을 것 같아요!

2023-06-30 07:07 UTC, thguss commented on src/main/java/com/sopterm/makeawish/domain/user/InternalTokenManager.java
> +                .toLocalDateTime().plusHours(3).atZone(KST).toInstant();
3시간으로 변경한 이유가 있나요??

2023-06-30 07:07 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/AuthService.java
> +@Transactional
`@Transactional(readOnly = true)`은 데이터의 변경을 막아주기 때문에 보통 Service 상단에 디폴트로 두고, 데이터 변경이 필요한 메소드에서만 `@Transactional`을 사용함으로써 안정성을 높입니다.
따라서 개인적으로 디폴트 값으로 `@Transactional(readOnly = true)`을 Service 상단에 두고, 필요한 메소드에서만 `@Transactional`을 사용하는 것이 바람직하다고 생각해요!

2023-06-30 07:07 UTC, thguss commented on src/main/java/com/sopterm/makeawish/service/AuthService.java
> +        String accessToken = tokenManager.createAuthToken(userId);
별거 아니긴 한데, createAuthRefreshToken 메서드가 추가되었으니 분별을 위해서 createAuthToken 메소드도 createAuthAccessToken 명으로 변경되면 더 좋을 것 같아요!

2023-06-30 07:08 UTC, thguss commented on src/main/java/com/sopterm/makeawish/domain/user/InternalMemberDetails.java
> +    private final String userNickName;
혹시 이 부분 Entity 변경에도 영향이 갈까요??

2023-06-30 13:37 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/controller/AuthController.java
> +    public ResponseEntity<ApiResponse> getToken(@Parameter(hidden = true) @AuthenticationPrincipal InternalMemberDetails memberDetails)
refresh토큰을 클라에서 전달해주면, @AuthenticationPrincipal로 세션 정보를 받아서 토큰에 해당하는 Member를 받을 수 있는것으로 알고있습니다!
refresh토큰을 받는것인데, refresh토큰을 검증한 후, internalmemberdetails 로 해당 유저의 엔티티를 받는것과 동일합니다!

2023-06-30 13:39 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/controller/AuthController.java
> +        System.out.println(memberDetails.getId());
어떻게 매번 빼먹을까요 ,, 꼼꼼한 리뷰 감사합니다 .. ❤️

2023-06-30 13:44 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/controller/CakeController.java
> +    public ResponseEntity<ApiResponse> getPresents(@Parameter(hidden = true) @AuthenticationPrincipal InternalMemberDetails memberDetails,
<img width="783" alt="image" src="https://github.com/Make-A-Wish-Sopt/Make-A-Wish-Server/assets/78431728/352a2ca1-cbed-4ff2-8712-bf82ef745225">
@AuthenticationPrincipal 선언하여 엔티티의 어댑터 객체 받아오는 것이 권장되는 방법이라고 본 이후 수정하였습니다!

2023-06-30 13:48 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/controller/CakeController.java
> +    public ResponseEntity<ApiResponse> getPresents(@Parameter(hidden = true) @AuthenticationPrincipal InternalMemberDetails memberDetails,
로그인 세션 정보를 어노테이션으로 간편하게 받을 수 있고, (Principal은 name메소드만 사용가능했지만) getId와 같은 커스텀한 메소드도 사용가능하다고 합니다! 그리고 Principal을 통해서 매 controller마다 유저를 검색해오는 중복되는 코드도 줄일 수 있어서 채택하게 되었습니다!

2023-06-30 13:50 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/domain/user/InternalMemberDetails.java
> +    private final String userNickName;
Entity에 영향이가지 않습니다! SpringSecurity에서 사용자 정보를 DB에서 접근해서 검색하지 않고, (세션이 유지되는 동안) 세션에서 가져온다고 해요!
그 Springsecurity가 세션에 저장하고있는 유저 정보입니다!

2023-06-30 13:51 UTC, yujindonut commented on src/main/java/com/sopterm/makeawish/domain/user/InternalTokenManager.java
> +                .toLocalDateTime().plusHours(3).atZone(KST).toInstant();
2시간은 또 너무 적은 것 같고 .. 4시간은 너무 긴것같아서 바꿨는데 refresh토큰이 발급되니까 소현님이 말씀하신대고 2시간으로 바꾸도록 할게요!

2023-06-30 23:51 UTC, wlwpfh approved these changes
수고하셨습니다! 새로운 내용 많이 배워가요! ! ! 👍 👍

2023-06-30 23:51 UTC, wlwpfh commented on src/main/java/com/sopterm/makeawish/controller/CakeController.java
> +@SecurityRequirement(name = "Authorization")
알아가요! !

2023-07-01 06:26 UTC, thguss commented on src/main/java/com/sopterm/makeawish/domain/user/InternalTokenManager.java
> +                .toLocalDateTime().plusHours(3).atZone(KST).toInstant();
@yujindonut 아 단순하게 궁금해서 물어본 거였어요 ㅎㅎ Refresh Token이 있으니 2시간도 괜찮을 것 같네용!

2023-07-01 06:27 UTC, thguss approved these changes
수고하셨습니다 :)

2023-07-01 07:00 UTC, merged